import {
  boolean,
  date,
  doublePrecision,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
} from 'drizzle-orm/pg-core';

export const jobs = pgTable(
  'jobs',
  {
    id: uuid().primaryKey().defaultRandom(),
    source: text().$type<'ba'>().notNull(),
    externalId: text().notNull(),
    title: text().notNull(),
    company: text().notNull(),
    occupation: text(),
    description: text().notNull(),
    city: text(),
    region: text(),
    postalCode: text(),
    latitude: doublePrecision(),
    longitude: doublePrecision(),
    fullTime: boolean(),
    partTime: boolean(),
    remote: boolean(),
    permanent: boolean(),
    salaryMinYear: integer(),
    salaryMaxYear: integer(),
    agency: boolean(),
    url: text().notNull(),
    publishedAt: date().notNull(),
    raw: jsonb().notNull(),
    importedAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [unique('jobs_source_external_id_unique').on(table.source, table.externalId)],
);
