CREATE TABLE "jobs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"source" text NOT NULL,
	"external_id" text NOT NULL,
	"title" text NOT NULL,
	"company" text NOT NULL,
	"occupation" text NOT NULL,
	"description" text NOT NULL,
	"city" text NOT NULL,
	"region" text,
	"postal_code" text,
	"latitude" double precision,
	"longitude" double precision,
	"full_time" boolean,
	"part_time" boolean,
	"remote" boolean,
	"permanent" boolean,
	"salary_min_year" integer,
	"salary_max_year" integer,
	"agency" boolean,
	"url" text NOT NULL,
	"published_at" date NOT NULL,
	"raw" jsonb NOT NULL,
	"imported_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "jobs_source_external_id_unique" UNIQUE("source","external_id")
);
